language: cpp
os:
- linux
compiler:
- clang
script:
- echo Ready to build archive
after_success:
- "./scripts/build_support.sh archive_stdlib"
env:
  global:
  - secure: NZjBccLOtmz1pd6nYHMMk3dB4QG8RXSySUrlsdH9qOqj53DwlnZte8JrSUeE/z6EWZYqTMlJZ+0/b/h2i1l/vlI8PKPbYCXsvJ556BuTUP/s0Lwx5GWkTvH8gCxxv7NripBdRv+V37CXD4Q8kHMFIRHx4qg+SZGi2s2FztWRcaCKJpyFrzUDJnU45LSTXhvB/4lowm/AKUAc8CMJaQh/pHSQWc1BxY7Uzs60Ft7vP9fzoiz2q7Dv+82hIjX01rf+NC/+7HxzAvKuOlh8TxNYH275BOQJu6uM+SVt+MMCP86BKq+8PuhrYgqBytwkSPb63HwgWzsywmuV5+I/A6LRxzSjZDiH+pKF/4BMcpWuECDt5Jf+7jwtmGmmwwwrqn6BX/5xOfG6uoL56TxkXw7YKq4WHJws0mnDvI2ZIsPUagmPLL0PXSmBa2gFLLiJSWLQVF1E1jc6u5FrEe9xwGFFpu5nBK1rg4dGL3kWT4fwSDpbxqf+d/GG5MFIqbGtzWB0+A76VByHrx4c87935NBbCNLMYFDDpHpX5gfdqDGhVMQrpvM7Jh0SvG9Lm8my+Z+Szw1e935UI9vLxys96dtWGoSaPQQmRy9ipX5axYdlidhTKQ9JKe0UM6NQs9YXdip+4HoT2n72Im0X5swNHou0zUpqqRkIxcciyB2jeFWHJhs=
  - secure: FDRw3DHq/qaky6KIhyiQ6nB9gAwTkhnoVLhqeF0cFEk3TlnqAJSArXHRnXxjzkiPogY6ANwHKkJJOW+5JBs+3e03RA6ohMCAyyEpNCLdkp/VtcUWomCVOj9sMtKVd3LqWjpLuvdfWQjODbWP/U+A19kAEugx3i4AHC4AeKxTuTf7sURak4o7PppJyKYSppdxx/tH2XA0+CsNUmCRivbpzlgLD8ZBvyATv0tvH9NtpAg/m2h+UrJO6ptUTN8VG9LbudoDBtECUdDoiwwDLIz2j5cyIQPpDSl+tDG7SXzV9n5vEFUhcYXJSDpVft2brZYCLDNNRZu0NW16BLt8TNFOFK/1KNTs6pE8Bjbwzg2CQfST0d8On7c0CR+D35lCMi4plDVN4nQhEINks7zf4FKHUjRlO5vSjkyjfhZ62sntboj0Rs2EHwElsGvLgFdbwsWzZQjkm/UiMOaVKkMs22O/x5v8yvtYB85SQOR50ISZ5ujw8yffmQAtkfQU79CpzwPlDh/6pAlXJeKlchTuxfN+7KkfIUctC33FvIoXA0iMprfZ0E8dpAPspUrdQidJKmbqIeEhfkhTKEsiUVwN2X2Od1VgGaX6rL3L7iUOsEuxxplQVv/sYyDc4l3jBTL21eKVizYy8xLCFS89GebEcgjcSK8dK/obleTRp8ZOrSvKQrY=
